INSERT INTO financial_institutions (id, name) VALUES
    (1, 'Banco do Brasil'),
    (2, 'Itaú Unibanco'),
    (3, 'Caixa Econômica Federal'),
    (4, 'Banco Bradesco'),
    (5, 'Santander Brasil'),
    (6, 'BTG Pactual'),
    (7, 'Banco Safra'),
    (8, 'Banco Votorantim'),
    (9, 'Banco Inter'),
    (10, 'Banco Original'),
    (11, 'Banco Pan'),
    (12, 'Nubank'),
    (13, 'PagSeguro'),
    (14, 'Cielo'),
    (15, 'XP Inc.'),
    (16, 'Picpay')