version: '3.8'
services:
  mysql:
    image: mysql:8.0.34
    container_name: financial-institutions-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financial_institutions
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data/financial_institutions-mysql:/var/lib/mysql