version: '3.8'
services:
 mysql:
  image: mysql:8.2.0
  restart: always
  environment:
    MYSQL_DATABASE: institution
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: devuser
    MYSQL_PASSWORD: devpasswd
  ports:
    - '3306:3306'
  volumes:
    - mysql_data:/var/lib/mysql
volumes:
  mysql_data: